#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct Column { pub name: String, pub data_type: String, pub primary_key: bool, pub nullable: bool, pub references: Option<ForeignKey> }
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ForeignKey { pub table: String, pub column: String }
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct Table { pub name: String, pub columns: Vec<Column> }
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct Schema { pub tables: Vec<Table> }
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum SqlDialect { Postgres, MySql, MariaDb, Sqlite, DynamoDb }

pub fn generate_ddl(schema: &Schema, dialect: SqlDialect) -> String { if dialect == SqlDialect::DynamoDb { return schema.tables.iter().map(|table| format!("// DynamoDB model\n{{ \"TableName\": \"{}\", \"PartitionKey\": \"id\" }}", table.name)).collect::<Vec<_>>().join("\n\n"); } schema.tables.iter().map(|table| { let columns = table.columns.iter().map(|column| column_to_sql(column, dialect)).collect::<Vec<_>>().join(",\n  "); format!("CREATE TABLE {} (\n  {}\n);", quote(&table.name, dialect), columns) }).collect::<Vec<_>>().join("\n\n") }
fn column_to_sql(column: &Column, dialect: SqlDialect) -> String { let mut sql = format!("{} {}", quote(&column.name, dialect), normalize_type(&column.data_type, dialect)); if column.primary_key { sql.push_str(" PRIMARY KEY"); } if !column.nullable { sql.push_str(" NOT NULL"); } if let Some(reference) = &column.references { sql.push_str(&format!(" REFERENCES {}({})", quote(&reference.table, dialect), quote(&reference.column, dialect))); } sql }
fn quote(identifier: &str, dialect: SqlDialect) -> String { match dialect { SqlDialect::MySql | SqlDialect::MariaDb => format!("`{identifier}`"), _ => format!("\"{identifier}\"") } }
fn normalize_type(data_type: &str, dialect: SqlDialect) -> String { match (data_type.to_ascii_lowercase().as_str(), dialect) { ("uuid", SqlDialect::MySql | SqlDialect::MariaDb) => "CHAR(36)".into(), ("timestamptz", SqlDialect::MySql | SqlDialect::MariaDb) | ("timestamptz", SqlDialect::Sqlite) => "DATETIME".into(), ("boolean", SqlDialect::Sqlite) => "INTEGER".into(), _ => data_type.to_uppercase() } }

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)] pub struct FakeRow(pub Vec<(String, String)>);
pub fn generate_fake_rows(table: &Table, count: usize) -> Vec<FakeRow> { const FIRST: [&str; 4] = ["Mia", "Noah", "Olivia", "Liam"]; const LAST: [&str; 4] = ["Williams", "Taylor", "Brown", "Wilson"]; (0..count).map(|index| { let n = index + 1; FakeRow(table.columns.iter().map(|column| { let kind = column.data_type.to_ascii_lowercase(); let value = if column.name == "email" { format!("{}.{}{}@example.dev", FIRST[index % 4].to_ascii_lowercase(), LAST[index % 4].to_ascii_lowercase(), n) } else if column.name.contains("name") { format!("{} {}", FIRST[index % 4], LAST[index % 4]) } else if kind.contains("int") || kind.contains("numeric") { n.to_string() } else if kind.contains("date") || kind.contains("time") { format!("2026-{:02}-{:02}T10:00:00Z", (n % 12) + 1, (n % 27) + 1) } else if kind == "uuid" { format!("00000000-0000-4000-8000-{n:012}") } else { format!("sample_{n}") }; (column.name.clone(), value) }).collect()) }).collect() }
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)] pub struct Migration { pub statements: Vec<String> }
pub fn diff_schemas(current: &Schema, target: &Schema, dialect: SqlDialect) -> Migration { let mut statements = Vec::new(); for desired in &target.tables { match current.tables.iter().find(|table| table.name == desired.name) { None => statements.push(generate_ddl(&Schema { tables: vec![desired.clone()] }, dialect)), Some(existing) => for column in &desired.columns { if !existing.columns.iter().any(|item| item.name == column.name) { statements.push(format!("ALTER TABLE {} ADD COLUMN {};", quote(&desired.name, dialect), column_to_sql(column, dialect))); } } } } Migration { statements } }
#[cfg(test)] mod tests { use super::*; fn users() -> Table { Table { name: "users".into(), columns: vec![Column { name: "id".into(), data_type: "uuid".into(), primary_key: true, nullable: false, references: None }, Column { name: "email".into(), data_type: "varchar(255)".into(), primary_key: false, nullable: false, references: None }] } } #[test] fn ddl_works() { assert!(generate_ddl(&Schema { tables: vec![users()] }, SqlDialect::Postgres).contains("CREATE TABLE \"users\"")); } #[test] fn fake_data_works() { assert_eq!(generate_fake_rows(&users(), 1)[0].0[1].1, "mia.williams1@example.dev"); } #[test] fn diff_works() { let mut target = users(); target.columns.push(Column { name: "created_at".into(), data_type: "timestamptz".into(), primary_key: false, nullable: false, references: None }); assert_eq!(diff_schemas(&Schema { tables: vec![users()] }, &Schema { tables: vec![target] }, SqlDialect::Postgres).statements.len(), 1); } }
